
export enum FoodCategory {
    LACTEOS = 'LACTEOS',
    CARNES = 'CARNES',
    VERDURAS = 'VERDURAS',
    FRUTAS = 'FRUTAS',
    CEREALES = 'CEREALES',
    LEGUMBRES = 'LEGUMBRES',
    ACEITES = 'ACEITES',
    CONDIMENTOS = 'CONDIMENTOS',
    BEBIDAS = 'BEBIDAS',
    ENLATADOS = 'ENLATADOS',
    PANADERIA = 'PANADERIA',
    EMBUTIDOS = 'EMBUTIDOS',
    OTROS = 'OTROS'
}
